cmd = "python -c '{opts.cmd}; print({opts.index})' &| tee -a {uid}/output.log"
uid = "xpert.logs/{opts.index}"

[opts]
cmd = 'import tensorflow as tf; import os; print(tf.random.normal([4, 4]) + tf.eye(4)); print(os.environ.get("CUDA_VISIBLE_DEVICES", "NOTFOUND"))'
index = [0, 1, 2, 3]

[proc]
num = 2

[proc.gpu]
indices = ["1", "2,4"]
