cmd = 'import tensorflow as tf; import os; print(tf.random.normal([4, 4]) + tf.eye(4)); print(os.environ.get("CUDA_VISIBLE_DEVICES", "NOTFOUND"))'
uid = "xpert.logs/{index}"

[[exp]]
cmd = "python -c '{cmd}; print(\"{index}\", \"{name}\")'"
name = "group.1"
index = [0, 1]

[[exp]]
cmd = "python -c '{cmd}; print({index}, {name})'"
name = '"group.2"'
index = [10, 20, 30, 40]

[resources]
restart = true
num_proc = 2
gpu_indices = ["1", "2,4"]
